const initialState = {
  // Define initial state below
  eventData: {
    sendData: [],
    openData: [],
    clickData: [],
    unsubscribeData: [],
    bounceData: []
  },
  eventDataJob: 0,
  eventDataJobState: '',
  emailInventory: {},
  emailInventoryJob: 0,
  emailInventoryJobState: '',
  templateInventory: {},
  templateInventoryJob: 0,
  templateInventoryJobState: '',
  categories: {},
  categoriesJob: 0,
  categoriesJobState: '',
  triggeredSends: {},
  triggeredSendsJob: 0,
  triggeredSendsJobState: '',
  cloudPages: {},
  cloudPagesJob: 0,
  cloudPagesJobState: '',
  dataExtensions: {},
  dataExtensionsJob: 0,
  dataExtensionsJobState: '',
  filterData: {},
  filterDataJob: 0,
  filterDataJobState: '',
  queries: [],
  queriesJob: 0,
  queriesJobState: '',
  automations: [],
  automationsJob: 0,
  automationsJobState: '',
  journeys: [],
  journeysJob: 0,
  journeysJobState: '',
  businessUnits: [],
  businessUnitsJob: 0,
  businessUnitsJobState: '',
  accountUsers: [],
  accountUsersJob: 0,
  accountUsersJobState: '',
  roles: [],
  rolesJob: 0,
  rolesJobState: '',
  subscribers: {
    allSubscribers: [],
    duplicateSubscribers: [],
    activeSubscribers: [],
    bouncedSubscribers: [],
    unsubscribedSubscribers: []
  },
  subscribersJob: 0,
  subscribersJobState: '',
  auditEvents: {
    items: []
  },
  auditEventsJob: 0,
  auditEventsJobState: '',
  accountInventorySelected: '',
  emailActivitySelected: '',
  subscribersSummarySelected: ''
  // ...
};

export default initialState;
